### ISSUE TITLE
Ruby claims gem extensions aren't built

### ISSUE THREAD

**Issue by jmacdonald** [matsadler/magnus#62]
First and foremost, thank you for all of your hard work on this project. Being able to write Ruby extensions in Rust with minimal fanfare is enticing; I'm eager to use this library!

I've been trying to build a Ruby gem that leverages magnus, and despite being able to build the gem itself without issue, when trying to consume it from another Ruby project, it complains that the native extensions aren't built:

`Ignoring rust_blank-0.1.0 because its extensions are not built. Try: gem pristine rust_blank --version 0.1.0`

To simplify things as much as possible, I've taken the `rust_blank` example from this repo and [extended it](https://github.com/jmacdonald/rust_blank/) with the bare minimum that highlights what I'm trying to do. From a clean slate within that repo, I've done the following:

1. Built the gem using `rake` in the root directory (provided you have the `rake-compiler` gem installed, this builds and tests the gem successfully)
2. Navigated into the `app/` subdirectory and run bundle, to install the path-referenced gem (runs without issue)
3. Run `bundle exec irb` to get an interactive shell to try the gem (loads, but displays the error above)

Can you help shed light on what I'm doing wrong here? Unlikely to be an issue, but for completeness' sake, I'm running Ruby `v3.1.3p185` and Rust `v1.67.1`.

**Comment by matsadler** [comment]
Hey, thanks for taking a look at this library and the kind words.

So I think this does work, you just need to ignore the error (see the transcript below of me trying it).

It's hitting some edge case with the integration of RubyGems, Bundler, and Bundler's path dependencies feature that generates that `extensions are not built` error even when everything is fine.

I don't think this is a Magnus/Rust issue, I think it's a problem any extension gem will run into. I tried the same thing with the [original, in C, `fast_blank`](https://github.com/SamSaffron/fast_blank) and got exactly the same error.

---

Here's how I tried it out:

Lets clone the project and run `bundle`:

``` sh
~/gemtest> git clone git@github.com:jmacdonald/rust_blank.git
Cloning into 'rust_blank'...
remote: Enumerating objects: 25, done.
remote: Counting objects: 100% (25/25), done.
remote: Compressing objects: 100% (21/21), done.
remote: Total 25 (delta 1), reused 25 (delta 1), pack-reused 0
Receiving objects: 100% (25/25), 1.37 MiB | 4.13 MiB/s, done.
Resolving deltas: 100% (1/1), done.
~/gemtest> cd rust_blank/app/
~/g/r/app> bundle
Resolving dependencies...
Fetching gem metadata from https://rubygems.org/.
Using bundler 2.4.6
Fetching rb_sys 0.9.65
Installing rb_sys 0.9.65
Using rust_blank 0.1.0 from source at `..`
Bundle complete! 1 Gemfile dependency, 3 gems now installed.
Bundled gems are installed into `./.bundle`
```

Ok, so bundler says it installed the gem, lets see if it works:

``` sh
~/g/r/app> bundle exec irb
Ignoring rust_blank-0.1.0 because its extensions are not built. Try: gem pristine rust_blank --version 0.1.0
```

Hummm, that doesn't look promising, lets try anyway:

```
irb(main):001:0> require "rust_blank"
~/src/bundle_test/rust_blank/lib/rust_blank.rb:3:in `require_relative': cannot load such file -- ~/src/bundle_test/rust_blank/lib/rust_blank/rust_blank (LoadError)                                                           
        from ~/src/bundle_test/rust_blank/lib/rust_blank.rb:3:in `<top (required)>'                                                                    
        from <internal:~/.rbenv/versions/3.2.0/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'                           
        from <internal:~/.rbenv/versions/3.2.0/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'                           
        from (irb):1:in `<main>'                                                
        from ~/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/irb-1.6.2/exe/irb:11:in `<top (required)>'                                               
        from ~/.rbenv/versions/3.2.0/bin/irb:25:in `load'              
        from ~/.rbenv/versions/3.2.0/bin/irb:25:in `<top (required)>'  
        from ~/.rbenv/versions/3.2.0/lib/ruby/site_ruby/3.2.0/bundler/cli/exec.rb:58:in `load'
	from ~/.rbenv/versions/3.2.0/lib/ruby/site_ruby/3.2.0/bundler/cli/exec.rb:58:in `kernel_load'
	from ~/.rbenv/versions/3.2.0/lib/ruby/site_ruby/3.2.0/bundler/cli/exec.rb:23:in `run'
	from ~/.rbenv/versions/3.2.0/lib/ruby/site_ruby/3.2.0/bundler/cli.rb:491:in `exec'
	from ~/.rbenv/versions/3.2.0/lib/ruby/site_ruby/3.2.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	from ~/.rbenv/versions/3.2.0/lib/ruby/site_ruby/3.2.0/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	from ~/.rbenv/versions/3.2.0/lib/ruby/site_ruby/3.2.0/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
	from ~/.rbenv/versions/3.2.0/lib/ruby/site_ruby/3.2.0/bundler/cli.rb:34:in `dispatch'
	from ~/.rbenv/versions/3.2.0/lib/ruby/site_ruby/3.2.0/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
	... 6 levels...
irb(main):002:0> 
```

Nope, looks like it the extension really wasn't built. What happens if we build it ourselves?

``` sh
~/g/r/app> cd ..
~/g/rust_blank> rake compile
mkdir -p tmp/arm64-darwin22/rust_blank/3.2.0
cd tmp/arm64-darwin22/rust_blank/3.2.0
~/.rbenv/versions/3.2.0/bin/ruby -I. -r.rake-compiler-siteconf.rb ../../../../ext/rust_blank/extconf.rb
cd -
cd tmp/arm64-darwin22/rust_blank/3.2.0
/usr/bin/make
generating target/release/librust_blank.dylib (release)
cargo rustc --target-dir target --manifest-path ../../../../ext/rust_blank/Cargo.toml --lib --release -- -C linker=clang -L native=~/.rbenv/versions/3.2.0/lib -L native=~/.rbenv/versions/3.2.0/lib -C link-arg=-Wl,-multiply_defined,suppress -l pthread -C link-arg=-Wl,-undefined,dynamic_lookup
   Compiling memchr v2.5.0
   Compiling proc-macro2 v1.0.47
   Compiling unicode-ident v1.0.5
   Compiling glob v0.3.0
   Compiling quote v1.0.21
   Compiling libc v0.2.137
   Compiling minimal-lexical v0.2.1
   Compiling cfg-if v1.0.0
   Compiling libloading v0.7.4
   Compiling regex-syntax v0.6.28
   Compiling bindgen v0.60.1
   Compiling clang-sys v1.4.0
   Compiling peeking_take_while v0.1.2
   Compiling bitflags v1.3.2
   Compiling shlex v1.1.0
   Compiling aho-corasick v0.7.19
   Compiling nom v7.1.1
   Compiling lazy_static v1.4.0
   Compiling lazycell v1.3.0
   Compiling rustc-hash v1.1.0
   Compiling shell-words v1.1.0
   Compiling syn v1.0.103
   Compiling rb-sys-env v0.1.1
   Compiling magnus v0.5.1
   Compiling regex v1.7.0
   Compiling cexpr v0.6.0
   Compiling magnus-macros v0.4.0
   Compiling rb-sys-build v0.9.64
   Compiling rb-sys v0.9.64
   Compiling rust_blank v0.2.0 (~/src/bundle_test/rust_blank/ext/rust_blank)
    Finished release [optimized] target(s) in 7.32s
cd -
mkdir -p tmp/arm64-darwin22/stage/lib/rust_blank
/usr/bin/make install target_prefix=
generating target/release/librust_blank.dylib (release)
cargo rustc --target-dir target --manifest-path ../../../../ext/rust_blank/Cargo.toml --lib --release -- -C linker=clang -L native=~/.rbenv/versions/3.2.0/lib -L native=~/.rbenv/versions/3.2.0/lib -C link-arg=-Wl,-multiply_defined,suppress -l pthread -C link-arg=-Wl,-undefined,dynamic_lookup
    Finished release [optimized] target(s) in 0.02s
installing rust_blank.bundle to ~/src/bundle_test/rust_blank/lib/rust_blank
/usr/bin/install -c -m 0755 rust_blank.bundle ~/src/bundle_test/rust_blank/lib/rust_blank
cp tmp/arm64-darwin22/rust_blank/3.2.0/rust_blank.bundle tmp/arm64-darwin22/stage/lib/rust_blank/rust_blank.bundle
```

All done, lets try again:

``` sh
~/g/rust_blank> cd app/
~/g/r/app> bundle exec irb
Ignoring rust_blank-0.1.0 because its extensions are not built. Try: gem pristine rust_blank --version 0.1.0
```

Uh oh, this again, well, lets just try anyway:

``` sh
irb(main):001:0> require "rust_blank"
=> true
irb(main):002:0> "".blank?
=> true
irb(main):003:0> "foo".blank?
=> false
```

Turns out it works, despite the error message.

**Comment by jmacdonald** [comment]
Well, that's good news, despite the fact that I should have tried that myself. 😅 Very much appreciate you taking the time to give this a spin and help me out! 🍻
